#!/usr/bin/env python
#-*- coding:utf-8 -*-

本程序主要功能：
1、批量命令操作(多线程并发)
2、批量文件分发（多线程并发）


1、参数介绍
python action.py -c command   :will send command to all server
python action.py -f source_filepath destination_filepath :will send file to all server user home dir

2、命令操作
E:\学习\GitHub\homework\day9\batch_action\bin>python action.py -c df -h
['192.168.0.110', '22', 'root', 'nihao123!']
['192.168.0.111', '22', 'root', 'nihao123!']
鏂囦欢绯荤粺          瀹归噺  宸茬敤  鍙敤 宸茬敤%% 鎸傝浇鐐?
/dev/sda3              19G  5.1G   14G  28% /
tmpfs                 492M     0  492M   0% /dev/shm
/dev/sda1             194M   27M  157M  15% /boot

Filesystem            Size  Used Avail Use% Mounted on
/dev/sda3              19G  4.6G   14G  25% /
tmpfs                 492M     0  492M   0% /dev/shm
/dev/sda1             194M   27M  157M  15% /boot

3、批量文件分发
E:\学习\GitHub\homework\day9\batch_action\bin>python action.py -f c:\haproxy.conf /tmp/shuaige
['192.168.0.110', '22', 'root', 'nihao123!']
['192.168.0.111', '22', 'root', 'nihao123!']
File is put done Source:c:\haproxy.conf Destination:/tmp/shuaige
File is put done Source:c:\haproxy.conf Destination:/tmp/shuaige

