#!/usr/bin/env python
#-*- coding:utf-8 -*-

博客地址：http://www.cnblogs.com/luotianshuai/p/5229978.html

GitHub地址：https://github.com/Tim-luo/homework/tree/master/day16


作业：

网页头部：
    --定义了网页头图标
    --定义了跑马灯实例

网页顶部：
    --使用BootStrap菜单栏
        --定义bootstrap菜单栏
        --定义bootstrap下拉菜单
        --定义bootstrap搜索框

网页中心：
    右侧：占比70%
        --定义部分连接按钮
        --定义发布功能，使用模态对话框
        --使用background-position & jQuery实现滑动效果
        --定义翻页功能
    左侧：占比30%
        --定义消息按钮
        --定义聊天狂
        --定义热点

定义返回顶部
