#!/usr/bin/env python
#-*- coding:utf-8 -*-

博客地址：http://www.cnblogs.com/luotianshuai/p/4930655.html
github地址：

本程序是3次登录认证的程序，3次登录失败后锁定账号：

1、运行程序:python login.py


2、程序测试
登录成功：
您好请输入您的用户名：tianshuai
您好请输入您的密码：123
欢迎tianshuai登录系统


登录失败：
您好请输入您的用户名：tianshuai
您好请输入您的密码：test
tianshuai的密码错误
您好请输入您的用户名：tianshuai
您好请输入您的密码：test
tianshuai的密码错误
您好请输入您的用户名：tianshuai
您好请输入您的密码：test
tianshuai的密码错误
您好请输入您的用户名：tianshuai
您好请输入您的密码：lskdjf
tianshuai用户账户已被锁定请联系管理员解锁
