# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 03:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.CharField(default='text', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u9690\u85cf'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_comment', to='web.Comment'),
        ),
    ]
