# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_userprofile_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=24, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_status', to='web.UserStatus'),
            preserve_default=False,
        ),
    ]
