# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('ctime', models.DateTimeField(auto_now=True)),
                ('uptime', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=32, null=True)),
                ('email2', models.GenericIPAddressField(blank=True, null=True, protocol='ipv4')),
                ('img', models.ImageField(blank=True, null=True, upload_to='upload')),
            ],
        ),
    ]
