# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('ctime', models.DateTimeField(auto_now=True)),
                ('uptime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
