# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 03:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gorup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='HostBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostbusiness', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=64)),
                ('hostip', models.CharField(max_length=64)),
                ('hostport', models.CharField(max_length=64)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Gorup')),
                ('hostbusiness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.HostBusiness')),
            ],
        ),
        migrations.CreateModel(
            name='HostStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoststatus', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Gorup')),
            ],
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='hoststatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.HostStatus'),
        ),
    ]
