#!/usr/bin/env python
#-*- coding:utf-8 -*-

#博客地址：
'''
http://www.cnblogs.com/luotianshuai/p/5058562.html
http://www.cnblogs.com/luotianshuai/p/5098408.html
http://www.cnblogs.com/luotianshuai/p/5111587.html
'''

