# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=32)),
                ('host_port', models.CharField(max_length=32)),
                ('host_ip', models.CharField(max_length=32)),
                ('host_business', models.CharField(max_length=32)),
                ('host_status', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=16)),
                ('passwords', models.CharField(max_length=32)),
            ],
        ),
    ]
