#!/usr/bin/env python
#-*- coding:utf-8 -*-

博客:
http://www.cnblogs.com/luotianshuai/p/5301343.html


用户名：luotianshuai@qq.com
密码：123




所有网页均使用装饰器判断用户是否已登录



路由规则:
    --默认打开网页都跳转到login页面.
        --login页面使用自动生成from表单==> {并优化输入错误后保留用户名!}
            --认证
                --前端认证 login页面结合js进行前端验证(此文下面注释1)
                --后端认证 增加后端认证(防止前端JS失效之后造成的影响)
                --使用自定义simple_tag 处理回执信息
                --使用session记录用户登录状态


    --登录成功跳转到index页面
        --使用装饰器判断用户是否登录
        --显示当登录的用户 并设置登出按钮
        ++点击资产进入管理页面



    --管理页面
        --使用模板语言对html进行渲染
            --复习使用并优化之前form表单代码

            --通过连表获取数据生成
            --通过ajax获取业务线/状态信息,然后生成select标签.

        --保存功能使用ajax进行后台提交数据并判断更新然后并回执信息
            --并设置回执信息5秒后自动隐藏

        --删除功能，使用ajax操作
            --并设置回执信息5秒后自动隐藏

        --添加资产列表，并进行用户输入认证

        --了不起的双下划线查询













注释1:
'''
html标签中,调用扩展js
        $(function(){
    		$.login('#Form','');
    	});


在valid.js中设置js


(function(jq){

	function ErrorMessage(container,msg){
		$error = container.find("div[class='sv-error-msg']");
		if($error.length>0){ //如果标签存在,设置内容
			$error.text(msg);
		}else{
			var temp = "<div class='sv-error-msg'>"+msg+"</label>";
			container.append(temp);//如果标签不存在添加div标签并把内容追加进去
		}

	}

	function EmptyError(container){
		$error = container.find("div[class='sv-error-msg']");
		if($error.length>0){
			$error.remove();//如果没有错误的时候,并且有报错标签的话把它移除
		}
	}

	jq.extend({
        'login':function(form,summaryStatusId){
                    $(form).find(':submit').click(function(){
                        var flag = true;

                        $(form).find(':input').each(function(){
                            var name = $(this).attr('name');
                            var label = $(this).attr('placeholder');
                            var val = $(this).val();
                            var $parent = $(this).parent();

                            if(!val || val.trim() == ''){ //如果为空
                                flag = false;
                                ErrorMessage($parent,label+'不能为空.');//把父标签和,内容传递给ErrorMessage方法
                                return false;
                            }
                            EmptyError($parent); //如果不为空把父标签传递给EmptyError方法
                        });
                        return flag;
                    });
                }
            });


})(jQuery)


'''