# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20160330_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(related_name='_userprofile_friends_+', to='web.UserProfile'),
        ),
    ]
