#!/usr/bin/env python
#-*- coding:utf-8 -*-

博客:



github:




装饰器判断用户是否已登录



路由规则:
    --默认打开网页都跳转到login页面.
        --login页面使用自动生成from表单.
            --并添加自定义from表单属性,使用ajax进行前端认证.使用前端和后端结合认证!

    --登录成功跳转
