# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 14:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostinfo',
            name='host_id',
            field=models.CharField(default=datetime.datetime(2016, 3, 18, 14, 53, 42, 391000, tzinfo=utc), max_length=32),
            preserve_default=False,
        ),
    ]
