#!/usr/bin/env python
#-*- coding:utf-8 -*-

博客地址：http://www.cnblogs.com/luotianshuai/p/5131053.html
GitHub地址：https://github.com/Tim-luo/homework/tree/master/day11

1、客户端ssh连接到服务器，执行脚本
2、密码认证，通过Mysql
3、3次密码锁定（可选）
4、认证成功打印功能
    输入IP直接登录
    p 显示可用的主机列表，并可以单独登录执行命令（跳板机）
    e 批量执行命令
    d 批量下载文件


需求：
1、执行修改某一用户用来做跳板用户并增加登录脚本
/usr/bin/python /opt/homework/day11/jumpserver_version1/bin/jumpserver_tianshuai.py
exit
2、使用跳板机用户进行登录
[root@localhost tim]# python /opt/homework/day11/jumpserver_version1/bin/jumpserver_tianshuai.py
**********welcom login jumpserver**********

Please input your contrl name: luotianshuai
Please input your pasword:
Welcom login luotianshuai jumpserver

            ###########################################################################
            #                                                                         #
            #                           Shuai JumpServer                              #
            #                                                                         #
            ###########################################################################
            1)Input p will show all server (only you can see,and you can chose ip login)
            2)Input e send command to all server
            3)Input d download file from all server
            4)Input u put file to all server

3、根据功能提示进行操作